repos:
  - repo: local
    hooks:
      - id: google-java-format
        name: Format Java code with google-java-format
        entry: google-java-format -i
        language: system
        # Only run on Java files
        files: \.java$

  - repo: local
    hooks:
      - id: gradle-check
        name: Run Gradle Check
        entry: ./gradlew check
        language: system
        pass_filenames: false
