spring:
  application:
    name: urlshortener
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: 8080
  baseurl: ${BASE_URL:http://localhost:8080/}
